FORMAT: 1A
HOST: underwriting.hellofloat.com
AUTHOR: alfred@hellofloat.com
CREATED: March 31, 2015

# Float-Demo
Float-Demo is an API designed for the Float demo web site and iOS app.  It is a subset of the general Float API which will have more functions such as KYC, issue card, etc.

# Group Users
All the functions related to working with users.

## User [/user]

+ Parameters:
  + email: `alfred@hellofloat.com` (string, required) - Unique email address of the user
  + mobile_phone: `123-456-7890` (string, optional) - Phone number
  + password: `12345678` (string, required)
  + password_confirmation `12345678` (string, required)
  + timezone: `America/Los_Angeles` (string, optional)
  + first_name: `alfred` (string, required)
  + last_name: `wechselberger` (string, required)
  + age: 30 (number, required)

### Store a User [POST]
Creates a new user.

+ Response 200 (application/json)

        { 
          "success": true, 
          "data": {
              "id": 16,
              "email": "alfred@hellofloat.com",
              "first_name": "alfred",
              "last_name": "wechselberger",
              "timezone": "America/Los_Angeles",
              "safe_to_loan": 550,
              "interest": 0.15,
              "profile": {
                "id":16,
                "verification": {
                  "mobile_phone_verified": false
                  "identity_verified": false,
                  "risk_verified": false
                },
                "photo": []
              }
            }
          }

